### ISSUE TITLE
Feil i validatePrefererteKanaler

### ISSUE THREAD

**Issue by jorgesti** [navikt/brukernotifikasjon-schemas#25]
Mulig feil i validatePrefererteKanaler. Prefererte kanaler skal i følge dokumentasjonen være valgfri, men hvis man ikke setter den i nyeste release får man feilmelding av typen: 
Cannot invoke "java.util.Collection.size()" because "array" is null of array of no.nav.brukernotifikasjon.schemas.Beskjed

Skyldes muligens at "field == null" ikke slår inn, da listen eksisterer, men er tom.

**Comment by Robert-Larsen** [comment]
Takk for beskjed, da skal vi få sett på det veldig snart.

**Comment by Robert-Larsen** [comment]
Ikke helt sikker på om jeg fikk med meg alt her. Den listen kan være null dersom ikke `withPrefererteKanaler()` er blitt kalt. 

Denne testen passerer:
`   @Test
    void skalGodtaTomListeSomPreferertKanal() {
        BeskjedBuilder builder = new BeskjedBuilder()
                .withFodselsnummer(expectedFodselsnr)
                .withGrupperingsId(expectedGrupperingsId)
                .withSikkerhetsnivaa(expectedSikkerhetsnivaa)
                .withLink(expectedLink)
                .withTekst(expectedTekst)
                .withTidspunkt(expectedTidspunkt)
                .withSynligFremTil(expectedSynligFremTil)
                .withEksternVarsling(true);
        assertDoesNotThrow(() -> builder.build());
    }`

Men mulig jeg har prøvd å gjenskape feil ting :) Har du et eksempel der dette ikke fungerer?

**Comment by jorgesti** [comment]
Da er det mulig jeg gjør noe snodig, men du kan evt se på koden
[SendNotifikasjon.kt](https://github.com/navikt/pensjon-etterlatte/blob/main/apps/etterlatte-notifikasjoner/src/main/kotlin/SendNotifikasjon.kt)
 
```
val beskjed = BeskjedBuilder()
            .withFodselsnummer(ident)
            .withGrupperingsId(grupperingsId)
            .withTekst(notifikasjonsTekst)
            .withTidspunkt(now)
            .withSynligFremTil(weekFromNow)
            .withSikkerhetsnivaa(sikkerhetsNivaa)
            .withEksternVarsling(eksternVarsling)
            .build()
```

Denne gir følgende feilmelding på brukernotifikasjon-schemas:1.2021.06.21-08.21-7998a39f216a: 
```
Error serializing Avro message
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.size()" because "array" is null of array of no.nav.brukernotifikasjon.schemas.Beskjed
	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:183)
```
men virker fint med forrige versjon.

**Comment by jorgesti** [comment]
Det virka fint, takk
